### ISSUE TITLE
Integration in tinyMediaManager 3.0

### ISSUE THREAD

**Issue by Lonerider2010** [ermshiperete/scraper-fernsehserien#1]
How do I integrate scraper-fernsehserien in tinyMediaManager 3.0?

**Comment by ermshiperete** [comment]
I've no idea since so far I never looked at 3.0. If you find out, create a pull request and I'm happy to integrate that.

Otherwise I'll eventually take a look once 3.0 is released and I get around to it.

**Comment by Lonerider2010** [comment]
Thanks for the information. Indeed I tried to convert scraper-fernsehserien to a .jar file and put it into the plugins directory of tmm 3.0, in the same manner as there are some more scrapers. But unfortunately that did not help, so I have no idea what to do else.

**Comment by Lonerider2010** [comment]
Are there plans to update scraper-fernsehserien to tmm 3.0, which has been released on 31.05.2019?

**Comment by ermshiperete** [comment]
Sorry, I'm too busy with other things right now, so I don't know when I will get to it.

**Comment by geosone** [comment]
are there any plans to update the scraper ?

**Comment by ermshiperete** [comment]
No, I don't have plans to update it. Unfortunately too many things have changed, and I don't have the necessary time. Sorry.
