### ISSUE TITLE
HowTo

### ISSUE THREAD

**Issue by Wotan1987** [ermshiperete/scraper-fernsehserien#2]
Hey,

könntest du mir bitte kurz erklären, wie ich deinen Scraper erfolgreich in TMM integrieren kann? Ich stelle mich anscheinend mal wieder zu blöd an :(

Vielen Dank für deine Arbeit!

**Comment by ermshiperete** [comment]
Sorry, I guess it doesn't work with TMM 3.0. And I currently don't have time to look into that.
